export const multiSelectAnatomy = [
  "root",
  "label",
  "description",
  "control",
  "values",
  "tag",
  "tag-remove",
  "placeholder",
  "clear",
  "chevron",
  "dropdown",
  "search",
  "content",
  "group",
  "group-label",
  "separator",
  "option",
  "option-button",
  "indicator",
  "icon",
  "option-content",
  "option-label",
  "option-description",
  "badge",
  "right-section",
  "empty"
] as const;

export type MultiSelectSlot = (typeof multiSelectAnatomy)[number];